version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    image: regulome-ui-nextjs
    volumes:
      - ".:/regulome-ui"
      - "/regulome-ui/node_modules"
      - "/regulome-ui/.next"
    command: npm run dev
    environment:
      - NODE_ENV=development
      # - SERVER_URL=http://localhost:3000
      # - BACKEND_URL=http://nginx:8000
      # - PUBLIC_BACKEND_URL=http://localhost:8000
    ports:
      - "3000:3000"
