version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    image: regulome-ui-nextjs
    volumes:
      - ".:/regulome-ui"
      - "/regulome-ui/node_modules"
      - "/regulome-ui/.next"
    command: npm test -- --coverage
    environment:
      - NODE_ENV=test
    ports:
      - "3000:3000"
