version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    image: regulome-ui-nextjs
    command: npm run start
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
