version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    image: regulome-ui-nextjs
    command: npm run start
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3000"

  nginxfe:
    build:
      context: ./docker/nginx/
    image: regulome-ui-nginx
    volumes:
      - "./docker/nginx/docker.prod-local.conf:/etc/nginx/nginx.conf"
    command: nginx -c /etc/nginx/nginx.conf -g 'daemon off; pid /dev/null;'
    ports:
      - "3000:8000"
    depends_on:
      - nextjs
