version: 2.1

workflows:
  regulome-ui-tests:
    jobs:
      - lint
      - cdk-mypy:
          requires:
            - lint
      - cdk-pytest:
          requires:
            - lint

jobs:
  lint:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/regulome-ui
    steps:
      - checkout
      - run: pip install pre-commit==2.17.0
      - run: pre-commit run --all-files

  cdk-mypy:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/regulome-ui/cdk/
    steps:
      - checkout:
          path: ~/regulome-ui
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: mypy .

  cdk-pytest:
    machine:
      image: ubuntu-2004:2023.04.2
      docker_layer_caching: true
    resource_class: medium
    working_directory: ~/regulome-ui/cdk/
    steps:
      - checkout:
          path: ~/regulome-ui
      - run: pyenv global 3.11
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: pytest tests/
